### ISSUE TITLE
Using with Phoenix 1.3 RC (blue_bird version 0.3.2 requires ~> 1.2)

### ISSUE THREAD

**Issue by DavidOliver** [rhazdon/blue_bird#14] opened 2017-06-22 19:13 UTC
I'm using Phoenix `1.3.0-rc.2`, and when I `mix deps.get` after adding BlueBird `~> 0.3.2` to `mix.exs` I get:

> Failed to use "phoenix" (versions 1.3.0-rc.0 to 1.3.0-rc.2) because
>   blue_bird (version 0.3.2) requires ~> 1.2 *
>   mix.exs specifies ~> 1.3.0-rc
> 
> \* This requirement does not match pre-releases. To match pre-releases include a pre-release in the requirement, such as: "~> 2.0-beta".
> 
> ** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}

Perhaps I misunderstand how dependencies work but I find this strange as `0.3.2`'s mix.exs has its Phoenix dependency as `~> 1.3.0-rc` whereas [at hex](https://hex.pm/packages/blue_bird) it shows as `~> 1.2`.

**Comment by woylie** [comment] 2017-06-22 19:31
That's odd indeed. Have you tried using `{:phoenix, "~> 1.3.0-rc.2", override: true}` in your project?

**Comment by DavidOliver** [comment] 2017-06-22 19:36
That does seem to allow BlueBird to install. Thanks! I previously misunderstood the instruction and added the override declaration to the BlueBird dep.

Do you know why hex shows `~> 1.2`?

**Comment by woylie** [comment] 2017-06-22 19:38
Unfortunately, I don't. @rhazdon?

**Comment by rhazdon** [comment] 2017-06-22 20:12
Hi @DavidOliver,

the problem is, that hex does not allow to publish packages with `rc` releases in the mix dependencies. This is the reason why I changed the Phoenix dependency to `{:phoenix, "~> 1.2"}` instead of `{:phoenix, "~> 1.3.0-rc"}` until Phoenix 1.3 will be released.

Sorry for the inconvenience. :)

**Closed as completed** 2017-06-22 21:23 UTC

**Comment by DavidOliver** [comment] 2017-06-22 21:48
Ah - good to know. Many thanks, both.
